name: CI – Shift Builder

on:
  push:
    paths:
      - 'projects/shift_builder/**'
  pull_request:
    paths:
      - 'projects/shift_builder/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r projects/shift_builder/requirements.txt
      - name: Run tests
        run: pytest projects/shift_builder/tests
